### ISSUE TITLE
Module contact: Lỗi cài đặt module ảo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1453]
Cài đặt module ảo contact, đến phần chọn dữ liệu mẫu, báo lôi:
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'vi-contact-bodytext' for key 'lang'' in /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/modules/contact/language/data_vi.php:68 Stack trace: #0 /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/modules/contact/language/data_vi.php(68): PDOStatement->execute() #1 /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/admin/modules/functions.php(420): include('/media/hongoctr...') #2 /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/admin/modules/setup.php(82): nv_setup_data_module('vi', 'lien-he', 1) #3 /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/admin/index.php(219): require('/media/hongoctr...') #4 {main} thrown in /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/modules/contact/language/data_vi.php on line 68
```

**Comment by vuthao** [comment]
Fixed
