### ISSUE TITLE
Lỗi chức năng đánh dấu đã xử lý module conntact

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3038]
Chức năng này không hoạt động được, error log có lỗi

```
[Sat, 27 Feb 2021 11:13:42 +0700] [v44.nukeviet4.my] [127.0.0.1] [Notice(8): Undefined index: processed_mark] [FILE: /modules/contact/admin/main.php] [LINE: 51] [TRACE:]
#1  LINE: 181   FILE: /admin/index.php

[Sat, 27 Feb 2021 11:13:42 +0700] [v44.nukeviet4.my] [127.0.0.1] [Error(1): Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name_key' cannot be null in D:\webroot\www\nukeviet4\v44.nukeviet4.my\vendor\vinades\nukeviet\Core\Database.php:611
Stack trace:
#0 D:\webroot\www\nukeviet4\v44.nukeviet4.my\vendor\vinades\nukeviet\Core\Database.php(611): PDOStatement->execute(NULL)
#1 D:\webroot\www\nukeviet4\v44.nukeviet4.my\includes\functions.php(2078): NukeViet\Core\NukeVietPDOStatement->execute()
#2 D:\webroot\www\nukeviet4\v44.nukeviet4.my\modules\contact\admin\main.php(51): nv_insert_logs('vi', 'contact', NULL, 'ID: 1', 1)
#3 D:\webroot\www\nukeviet4\v44.nukeviet4.my\admin\index.php(181): require('D:\\webroot\\www\\...')
#4 {main}
  thrown] [FILE: /vendor/vinades/nukeviet/Core/Database.php] [LINE: 611]

```

Nguyên nhân thiếu lang khi ghi log

**Comment by hoaquynhtim99** [comment]
Lỗi
```
Nên chú ý: Undefined index: reply_aid in file /modules/contact/admin/view.php on line 109
```

**Comment by hoaquynhtim99** [comment]
Ngoài ra, khi đánh dấu đã xử lý thì đồng thời cần cập nhật `is_read=1` luôn. Hiện tại đánh dấu đã xử lý thì liên hệ đó vẫn đang gọi là "Chưa xem"
