### ISSUE TITLE
Lỗi hàm post_async

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3483]
```
[Wed, 06 Jul 2022 09:57:40 +0700] [........] [ip.ip.ip.ip] [Warning(2): stream_socket_client(): php_network_getaddresses: getaddrinfo for ........ failed: Name or service not known] [FILE: /includes/functions.php] [LINE: 2981]
[Wed, 06 Jul 2022 09:57:40 +0700] [........] [ip.ip.ip.ip] [Error(1): Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/.../includes/functions.php:3003
Stack trace:
#0 /home/.../includes/functions.php(3003): fwrite()
#1 /home/.../includes/mainfile.php(149): post_async()
#2 /home/.../index.php(25): require('...')
#3 {main}
  thrown] [FILE: /includes/functions.php] [LINE: 3003]
```

**Comment by hoaquynhtim99** [comment]
Môi trường nginx + php-fpm

**Comment by anhtunguyen** [comment]
Đã thay stream_socket_client và fsockopen được sử dụng trong hàm post_async bằng curl. Lỗi trên không còn xuất hiện.
