### ISSUE TITLE
[NukeViet 4.6] Cài đặt xong không đăng nhập được quản trị

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3541]
Lỗi

```
[Sat, 07 Jan 2023 11:19:16 +0100] [v46.nukeviet4.my] [127.0.0.1] [Error(1): Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tb1.log_period' in 'field list'' in D:\webroot\www\nukeviet4\v46.nukeviet4.my\vendor\vinades\nukeviet\Core\Database.php:547
Stack trace:
#0 D:\webroot\www\nukeviet4\v46.nukeviet4.my\vendor\vinades\nukeviet\Core\Database.php(547): PDO->query('SELECT tb1.role...')
#1 D:\webroot\www\nukeviet4\v46.nukeviet4.my\includes\cronjobs\apilogs_autodel.php(26): NukeViet\Core\Database->query('SELECT tb1.role...')
#2 [internal function]: cron_apilogs_autodel()
#3 D:\webroot\www\nukeviet4\v46.nukeviet4.my\includes\core\cronjobs.php(81): call_user_func_array('cron_apilogs_au...', Array)
#4 D:\webroot\www\nukeviet4\v46.nukeviet4.my\includes\mainfile.php(465): require('D:\\webroot\\www\\...')
#5 D:\webroot\www\nukeviet4\v46.nukeviet4.my\index.php(38): require('D:\\webroot\\www\\...')
#6 {main}
  thrown] [FILE: /vendor/vinades/nukeviet/Core/Database.php] [LINE: 547] [REQUEST: /index.php]
[Sat, 07 Jan 2023 11:19:18 +0100] [v46.nukeviet4.my] [127.0.0.1] [Error(1): Call to undefined function NukeViet\Core\session_create_id()] [FILE: /vendor/vinades/nukeviet/Core/Request.php] [LINE: 1655] [REQUEST: /admin/index.php]

```

**Comment by hoaquynhtim99** [comment]
Lỗi này xuất hiện nếu chạy PHP 5.6, PHP 8.1 không bị

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh cài thử bằng php5.6 vẫn thấy bình thường. Theo lỗi em đưa lên thì thiếu cột "log_period" trong bảng "nv4_api_role". Em kiểm tra xem có nó sau khi cài đặt không?

**Comment by hoaquynhtim99** [comment]
Hiện không còn thấy lỗi nữa nên close
