### ISSUE TITLE
Нужна помощь по локализации языка

### ISSUE THREAD

**Issue by arzemas** [nukeviet/nukeviet#3634]
Tôi cài đặt NukeViet 4.5.03 php 8.1 trên máy chủ
Mình tải file vi tiếng việt về đổi tên thành ngôn ngữ ru nạp vào hệ thống đặt làm main
Đang tải dữ liệu từ phiên bản trước vào [MySQL]
Tôi tạo một tin mới, điền vào các trường bắt buộc và nhấp vào nút lưu, tôi nhận được màn hình trắng và báo lỗi

1. Устанавливаю на сервер NukeViet 4.5.03 php 8.1
2. Выкачиваю файл вьетнамского языка vi и переименовываю в язык ru, загружаю его в систему и назначаю основным 
3. Загружаю в [MySQL] данные предыдущей версии
4. Создаю новую новость, заполняю обязательные поля и нажимаю кнопку сохранить, получаю белый экран и ошибку
5. Error on file /vendor/vinades/nukeviet/Core/Database.php line 563:
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_key' in 'field list' in /var/www/arzemas/data/www/nukeviet.vn/vendor/vinades/nukeviet/Core/Database.php:563
Stack trace:
#0 /var/www/arzemas/data/www/nukeviet.vn/vendor/vinades/nukeviet/Core/Database.php(563): PDO->exec('INSERT INTO nv4...')
#1 /var/www/arzemas/data/www/nukeviet.vn/modules/news/Log/Log.php(79): NukeViet\Core\Database->exec('INSERT INTO nv4...')
#2 /var/www/arzemas/data/www/nukeviet.vn/modules/news/Shared/Logs.php(53): NukeViet\Module\news\Log\Log->save()
#3 /var/www/arzemas/data/wwwnukeviet.vn/modules/news/admin/content.php(1209): NukeViet\Module\news\Shared\Logs::saveLogStatusPost(252, 4)
#4 /var/www/arzemas/data/www/nukeviet.vn/admin/index.php(182): require('/var/www/arzema...')
#5 {main}
  thrown
Спасибо.

**Comment by arzemas** [comment]
Не актуально, можно удалить.
Спасибо.

**Comment by arzemas** [comment]
Можно закрыть

**Comment by arzemas** [comment]
Можно закрыть
